services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4444:8080" # дефолтный порт вебпака 8080
    # environment:
    #   - NODE_ENV=development
    volumes:
      - .:/app # Синхронизация кода
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    # environment:
    #   - NODE_ENV=production