FROM node:22-alpine as build
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install
COPY . .
RUN pnpm run build

FROM nginx:alpine as prod
COPY --from=build /app/dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
CMD ["nginx","-g","daemon off;"]